name: Laravel Continuous Integration

on:
  push:
    branches: ["master"]

jobs:
  test:
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: members-only_db
      DB_USERNAME: user
      DB_PASSWORD: password
      JWT_SECRET: THISISATESTSECRET
      TEST_BEARER_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTcsInVzZXJuYW1lIjoiYWRtaW5AZ21haWwuY29tIiwibWVtYmVyc2hpcC1zdGF0dXMiOiJpbmFjdGl2ZSJ9.HXC-RkfS-NcVXTqUhBi-p2D6dadeWyqZgXcjpjwgUxs
      APP_KEY: base64:yj4IkUzjUqxmtAadEVJ5UJ6k1D8jMfah6+LwYWYbka0=

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: members-only_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code From the Repository
        uses: actions/checkout@v2

      - name: Install PHP and Dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo_mysql
      - name: Install Composer Dependencies
        run: composer install

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Migrate tables to database
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test
